openapi: 3.0.0
info:
  title: Country API
  description: "API to fetch all countries with their provinces"
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /countries:
    get:
      summary: Retrieve list of countries with their provinces
      description: "Returns an array of country objects with their respective provinces."
      tags:
        - Countries
      operationId: getAllCountriesAndProvinces
      responses:
        '200':
          description: A list of countries with provinces.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                      example: "FR"
                      description: "The country code."
                    name:
                      type: string
                      example: "France"
                      description: "The name of the country."
                    provinces:
                      type: array
                      description: "List of provinces for the country."
                      items:
                        type: object
                        properties:
                          code:
                            type: string
                            example: "IDF"
                            description: "The province code."
                          name:
                            type: string
                            example: "Île-de-France"
                            description: "The name of the province."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unexpected error occurred."
