openapi: 3.0.0
info:
  title: Country API
  description: "API to fetch countries and provinces"
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /countries:
    get:
      summary: Retrieve list of countries
      description: "Returns an array of country objects."
      tags:
        - Countries
      operationId: getCountries
      responses:
        '200':
          description: A list of countries.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                      example: "FR"
                      description: "The country code."
                    name:
                      type: string
                      example: "France"
                      description: "The name of the country."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unexpected error occurred."

  /countries/{countryCode}/provinces:
    get:
      summary: Retrieve list of provinces for a specific country
      description: "Returns an array of provinces for the given country code."
      tags:
        - Countries
      operationId: getProvincesByCountryCode
      parameters:
        - name: countryCode
          in: path
          required: true
          description: The country code (ISO 3166-1 alpha-2 format) to fetch provinces for.
          schema:
            type: string
            example: "FR"
      responses:
        '200':
          description: A list of provinces.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                      example: "IDF"
                      description: "The province code."
                    name:
                      type: string
                      example: "Île-de-France"
                      description: "The name of the province."
        '400':
          description: Invalid country code provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid country code."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unexpected error occurred."
